In [1]:
from google.colab import files
import pandas as pd

# Subir archivo
uploaded = files.upload()

# Reemplaza el nombre si es diferente
df = pd.read_csv(
    "Data_Limpia_2010_2024 V2.csv",
    sep=";",
    decimal=","
)

df.head()

Saving Data_Limpia_2010_2024 V2.csv to Data_Limpia_2010_2024 V2.csv

,Fecha,Mes,Año,Día,PRECIPITACIÓN,TMAX,TMIN,TPROM,HR,RAD_SOL,RAD_SOL_original,mes
0,2010-01-01,1,2010,1,0.0,24.300000,17.928889,21.114444,84.522612,234.533392,3044.20,1
1,2010-01-02,1,2010,2,0.0,24.520000,17.950238,21.235119,84.719272,234.533392,3103.00,1
2,2010-01-03,1,2010,3,0.0,24.466667,18.014476,21.240571,81.879385,234.533392,2700.00,1
3,2010-01-04,1,2010,4,0.0,24.514286,18.177333,21.345810,83.381286,234.533392,3634.00,1
4,2010-01-05,1,2010,5,0.0,24.771429,18.307619,21.539524,82.602736,22.440000,22.44,1

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5293 entries, 0 to 5292
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fecha             5293 non-null   object
 1   Mes               5293 non-null   int64
 2   Año               5293 non-null   int64
 3   Día               5293 non-null   int64
 4   PRECIPITACIÓN     5293 non-null   float64
 5   TMAX              5293 non-null   float64
 6   TMIN              5293 non-null   float64
 7   TPROM             5293 non-null   float64
 8   HR                5293 non-null   float64
 9   RAD_SOL           5293 non-null   float64
 10  RAD_SOL_original  5293 non-null   float64
 11  mes               5293 non-null   int64
dtypes: float64(7), int64(4), object(1)
memory usage: 496.3+ KB

In [3]:
df.columns

Index(['Fecha', 'Mes', 'Año', 'Día', 'PRECIPITACIÓN', 'TMAX', 'TMIN', 'TPROM',
       'HR', 'RAD_SOL', 'RAD_SOL_original', 'mes'],
      dtype='object')

In [4]:
df.describe()

,Mes,Año,Día,PRECIPITACIÓN,TMAX,TMIN,TPROM,HR,RAD_SOL,RAD_SOL_original,mes
count,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000,5293.000000
mean,6.590402,2016.859059,15.731721,3.950104,24.067931,19.131088,21.599510,86.397159,202.035847,715.424510,6.590402
std,3.473417,4.327941,8.800156,10.431776,1.122336,2.062524,1.417559,8.041468,280.864772,1061.388327,3.473417
min,1.000000,2010.000000,1.000000,0.000000,20.371429,13.945714,17.190000,50.000000,6.160000,6.160000,1.000000
25%,4.000000,2013.000000,8.000000,0.000000,23.400000,17.528730,20.689248,82.568128,18.610000,18.610000,4.000000
50%,7.000000,2017.000000,16.000000,0.000000,24.056535,18.987891,21.615714,87.170466,23.050000,23.050000,7.000000
75%,10.000000,2020.000000,23.000000,3.000000,24.742857,20.740000,22.548508,92.000000,234.533392,1007.000000,10.000000
max,12.000000,2024.000000,31.000000,189.000000,28.342857,26.000000,26.471429,100.000000,1197.000000,3994.000000,12.000000

In [5]:
# Convertir Fecha a datetime
df['Fecha'] = pd.to_datetime(df['Fecha'])

# Crear variable año-mes
df['year_month'] = df['Fecha'].dt.to_period('M')

# Verificar
df[['Fecha', 'year_month']].head()

       Fecha year_month
0 2010-01-01    2010-01
1 2010-01-02    2010-01
2 2010-01-03    2010-01
3 2010-01-04    2010-01
4 2010-01-05    2010-01

## ESTRÉS TÉRMICO MENSUAL (ET)
Con el fin de cuantificar el impacto de la temperatura máxima sobre el cultivo de cacao, se construyó la variable Estrés Térmico Mensual (ET), la cual mide el grado de desviación de la temperatura máxima diaria respecto al valor óptimo para el desarrollo fisiológico del cultivo. Para su cálculo, se consideró como temperatura óptima central un valor de 28 °C, con un rango de tolerancia entre 24 °C y 32 °C, de acuerdo con la literatura agroclimática del cacao.

A nivel diario, el estrés térmico se estimó como la desviación absoluta de la temperatura máxima diaria (TMAX) respecto al valor óptimo, normalizada en una escala entre 0 y 1. Posteriormente, esta variable diaria fue agregada a escala mensual mediante el promedio de los valores diarios, obteniendo así el Estrés Térmico Mensual (ET).

En el conjunto de datos final, esta variable se almacena en la columna denominada ET, indexada por el período year_month, y toma valores continuos entre 0 (condiciones térmicas óptimas) y 1 (alto nivel de estrés térmico). Esta variable constituye uno de los componentes fundamentales del Índice de Estrés Agroclimático Mensual del Cacao (IEAM-C) y se utiliza como insumo para el posterior modelado con técnicas de machine learning.

ET ∈ [0, 1]

0 = condición térmica óptima

1 = alta desviación respecto al óptimo térmico del cacao

El Estrés Térmico Mensual (ET) es una variable normalizada que toma valores entre 0 y 1, donde valores bajos indican condiciones térmicas cercanas al óptimo para el cultivo de cacao y valores altos representan una mayor desviación respecto a dicho óptimo. Para facilitar su interpretación agronómica, el ET se clasifica en los siguientes rangos:





| **Rango ET** | **Nivel de estrés térmico** | **Interpretación agronómica**                                               |
| ------------ | --------------------------- | --------------------------------------------------------------------------- |
| 0.00 – 0.20  | Muy bajo                    | Condiciones térmicas cercanas al óptimo para el desarrollo del cacao        |
| 0.21 – 0.40  | Bajo                        | Leve desviación térmica, sin impacto significativo en el cultivo            |
| 0.41 – 0.60  | Moderado                    | Estrés térmico perceptible, con posible afectación de procesos fisiológicos |
| 0.61 – 0.80  | Alto                        | Estrés térmico elevado, con riesgo para floración y llenado de mazorca      |
| 0.81 – 1.00  | Muy alto                    | Condiciones térmicas adversas, con alto riesgo agronómico                   |


Estos rangos permiten clasificar los meses según su nivel de estrés térmico y facilitan el análisis comparativo temporal, así como la integración de esta variable dentro del Índice de Estrés Agroclimático Mensual del Cacao (IEAM-C).

| Expresión                            |
| ------------------------------------ |
| **ETₘ = ( Σᵈ I(T_d > T_opt) ) / Dₘ** |


| Símbolo   | Descripción                                               |
| --------- | --------------------------------------------------------- |
| **ETₘ**   | Índice de Estrés Térmico del mes *m*                      |
| **Dₘ**    | Número total de días del mes *m*                          |
| **T_d**   | Temperatura diaria considerada                            |
| **T_opt** | Umbral térmico óptimo para el cultivo de cacao            |
| **I(·)**  | Función indicadora: 1 si T_d > T_opt, 0 en caso contrario |

In [6]:
df['estres_termico_dia'] = (
    abs(df['TMAX'] - 28) / 8
).clip(0, 1)

In [7]:
df.columns

Index(['Fecha', 'Mes', 'Año', 'Día', 'PRECIPITACIÓN', 'TMAX', 'TMIN', 'TPROM',
       'HR', 'RAD_SOL', 'RAD_SOL_original', 'mes', 'year_month',
       'estres_termico_dia'],
      dtype='object')

In [8]:
# Construcción del Estrés Térmico Mensual (ET)
df_ET_mensual = (
    df
    .groupby("year_month")
    .agg(
        dias_mes=("estres_termico_dia", "count"),
        dias_estres=("estres_termico_dia", "sum")
    )
    .reset_index()
)

# Cálculo del índice ET
df_ET_mensual["ET"] = df_ET_mensual["dias_estres"] / df_ET_mensual["dias_mes"]

# Visualización inicial
df_ET_mensual.head()

  year_month  dias_mes  dias_estres        ET
0    2010-01        31    10.078452  0.325111
1    2010-02        28     6.714286  0.239796
2    2010-03        31     8.560714  0.276152
3    2010-04        30    15.326786  0.510893
4    2010-05        31    15.500000  0.500000

In [9]:
df_ET_mensual.describe()

         dias_mes  dias_estres          ET
count  174.000000   174.000000  174.000000
mean    30.419540    14.952944    0.491159
std      0.827188     3.610596    0.116921
min     28.000000     3.310714    0.106797
25%     30.000000    12.930014    0.421023
50%     31.000000    15.040308    0.493198
75%     31.000000    17.086632    0.555236
max     31.000000    24.357143    0.785714

In [10]:
# Total de meses
total_meses = len(df_ET_mensual)

# Meses en riesgo térmico
meses_riesgo = df_ET_mensual[df_ET_mensual["ET"] >= 0.61].shape[0]

# Porcentaje de meses en riesgo
porcentaje_riesgo = (meses_riesgo / total_meses) * 100

total_meses, meses_riesgo, porcentaje_riesgo

(174, 27, 15.517241379310345)

In [11]:
df_mensual = df_ET_mensual.copy()

In [12]:
df_mensual.head()

  year_month  dias_mes  dias_estres        ET
0    2010-01        31    10.078452  0.325111
1    2010-02        28     6.714286  0.239796
2    2010-03        31     8.560714  0.276152
3    2010-04        30    15.326786  0.510893
4    2010-05        31    15.500000  0.500000

## Estrés Hídrico Mensual (EH)

El Estrés Hídrico Mensual (EH) es un índice agroclimático que representa la proporción de días dentro de un mes en los que la disponibilidad hídrica resulta insuficiente para el desarrollo adecuado del cultivo de cacao. Este indicador permite identificar periodos con potencial limitación hídrica, los cuales pueden afectar procesos fisiológicos clave del cultivo, como la floración, el cuajado de frutos y el llenado de mazorcas.

En el presente estudio, el estrés hídrico diario se define como una variable binaria, en la cual un día es clasificado como estresante cuando la precipitación diaria es inferior a un umbral mínimo de 1 mm. Este valor es comúnmente utilizado en estudios agroclimáticos en regiones tropicales para identificar días secos efectivos. A partir de esta variable diaria, el índice mensual se calcula como la razón entre el número de días con estrés hídrico y el total de días del mes correspondiente.

El Estrés Hídrico Mensual se calcula mediante la siguiente expresión:

EH_m = (Número de días con estrés hídrico en el mes) / (Número total de días del mes)

El índice EH toma valores entre 0 y 1, donde valores cercanos a 0 indican condiciones hídricas favorables y valores cercanos a 1 reflejan una alta frecuencia de días con déficit hídrico. Este indicador no tiene como objetivo la predicción de condiciones climáticas futuras, sino la caracterización y clasificación del comportamiento agroclimático histórico mensual, sirviendo como insumo para la generación de escenarios de apoyo a la planificación agrícola del cultivo de cacao.

In [13]:
# =====================================================
# Normalización de nombres de columnas
# =====================================================

df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(' ', '_')
      .str.normalize('NFKD')
      .str.encode('ascii', errors='ignore')
      .str.decode('utf-8')
)

df.columns

Index(['fecha', 'mes', 'ano', 'dia', 'precipitacion', 'tmax', 'tmin', 'tprom',
       'hr', 'rad_sol', 'rad_sol_original', 'mes', 'year_month',
       'estres_termico_dia'],
      dtype='object')

In [14]:
# ============================================================
# CÁLCULO DEL ESTRÉS HÍDRICO (EH)
# Nivel diario → agregación mensual → integración al modelo
# ============================================================

# ------------------------------------------------------------
# 1. Estrés hídrico diario
# Un día presenta estrés hídrico si la precipitación < 1 mm
# ------------------------------------------------------------

df['estres_hidrico_dia'] = (df['precipitacion'] < 1).astype(int)

# ------------------------------------------------------------
# 2. Agregación mensual
# Se calcula la proporción de días con estrés hídrico por mes
# ------------------------------------------------------------

eh_mensual = (
    df.groupby('year_month')
      .agg(
          EH=('estres_hidrico_dia', 'mean')
      )
      .reset_index()
)

# ------------------------------------------------------------
# 3. Integración del EH mensual en el DataFrame del modelo
# ------------------------------------------------------------

df_mensual = df_mensual.merge(
    eh_mensual,
    on='year_month',
    how='left'
)

# ------------------------------------------------------------
# 4. Verificación rápida
# ------------------------------------------------------------

df_mensual[['year_month', 'ET', 'EH']].head()
df_mensual[['ET', 'EH']].describe()

               ET          EH
count  174.000000  174.000000
mean     0.491159    0.675659
std      0.116921    0.135164
min      0.106797    0.300000
25%      0.421023    0.580645
50%      0.493198    0.677995
75%      0.555236    0.774194
max      0.785714    0.935484

In [15]:
df_mensual.head()
df_mensual.describe()

         dias_mes  dias_estres          ET          EH
count  174.000000   174.000000  174.000000  174.000000
mean    30.419540    14.952944    0.491159    0.675659
std      0.827188     3.610596    0.116921    0.135164
min     28.000000     3.310714    0.106797    0.300000
25%     30.000000    12.930014    0.421023    0.580645
50%     31.000000    15.040308    0.493198    0.677995
75%     31.000000    17.086632    0.555236    0.774194
max     31.000000    24.357143    0.785714    0.935484

In [16]:
# ============================================================
# LIMPIEZA FINAL DEL DATAFRAME MENSUAL
# Eliminar variables intermedias de conteo
# ============================================================

columnas_intermedias = [
    'dias_mes',
    'dias_estres'
]

df_mensual = df_mensual.drop(columns=columnas_intermedias, errors='ignore')

# Verificación final del modelo
df_mensual.head()
df_mensual.describe()

               ET          EH
count  174.000000  174.000000
mean     0.491159    0.675659
std      0.116921    0.135164
min      0.106797    0.300000
25%      0.421023    0.580645
50%      0.493198    0.677995
75%      0.555236    0.774194
max      0.785714    0.935484

In [17]:
df_mensual.head()

  year_month        ET        EH
0    2010-01  0.325111  0.935484
1    2010-02  0.239796  0.607143
2    2010-03  0.276152  0.612903
3    2010-04  0.510893  0.633333
4    2010-05  0.500000  0.516129

## El Estrés por Radiación Solar Mensual (ER)
se define como la proporción de días dentro de un mes en los que la radiación solar normalizada alcanza valores elevados, representando condiciones potencialmente adversas para el cultivo de cacao. Dado que el cacao es una especie adaptada a ambientes de sombra parcial, la ocurrencia recurrente de altos niveles de radiación puede generar estrés fisiológico, incrementar la demanda hídrica y afectar negativamente el desarrollo del cultivo.

En este estudio, la radiación solar se aborda como una variable normalizada, por lo que el estrés radiativo se establece mediante un umbral relativo, considerando como día con estrés por radiación aquel en el que la radiación solar normalizada es mayor o igual a 0.75. El índice ER se calcula a nivel mensual como el promedio de la variable diaria binaria, lo cual equivale a la proporción de días con radiación elevada respecto al total de días del mes. Finalmente, el índice se clasifica en niveles de riesgo bajo, moderado y alto, con el fin de apoyar la planificación agrícola del cultivo de cacao.

#Rangos

| ER mensual       | Nivel de riesgo | Interpretación                                 |
| ---------------- | --------------- | ---------------------------------------------- |
| ER < 0.30        | Bajo            | Condiciones de radiación mayormente favorables |
| 0.30 ≤ ER < 0.60 | Moderado        | Exposición frecuente a radiación elevada       |
| ER ≥ 0.60        | Alto            | Estrés radiativo severo                        |


# Valores optimos

| Variable                    | Valor / rango de referencia | Interpretación agronómica        |
| --------------------------- | --------------------------- | -------------------------------- |
| Tipo de cultivo             | Sotobosque                  | Requiere sombra parcial          |
| Exposición solar óptima     | Moderada                    | Favorece fotosíntesis sin estrés |
| Radiación solar elevada     | Percentil ≥ 75              | Riesgo de estrés radiativo       |
| Radiación solar normalizada | 0 – 1                       | Variable relativa, no absoluta   |

In [18]:
# ============================================================
# CORRECCIÓN DEL ESTRÉS POR RADIACIÓN SOLAR (ER)
# Umbral basado en percentil histórico
# ============================================================

# Calcular umbral estadístico (percentil 75)
umbral_radiacion = df['rad_sol'].quantile(0.75)

# Estrés por radiación diario (definición corregida)
df['estres_radiacion_dia'] = (df['rad_sol'] >= umbral_radiacion).astype(int)

# Agregación mensual
er_mensual = (
    df.groupby('year_month')
      .agg(
          ER=('estres_radiacion_dia', 'mean')
      )
      .reset_index()
)

# Eliminar ER previo si existe (evitar duplicados)
df_mensual = df_mensual.drop(columns=['ER'], errors='ignore')

# Integrar ER corregido al modelo
df_mensual = df_mensual.merge(
    er_mensual,
    on='year_month',
    how='left'
)

# Verificación
df_mensual[['ET', 'EH', 'ER']].describe()

               ET          EH          ER
count  174.000000  174.000000  174.000000
mean     0.491159    0.675659    0.256949
std      0.116921    0.135164    0.279322
min      0.106797    0.300000    0.000000
25%      0.421023    0.580645    0.000000
50%      0.493198    0.677995    0.116240
75%      0.555236    0.774194    0.466667
max      0.785714    0.935484    1.000000

## Estrés por Humedad Relativa Mensual (EHR)

La humedad relativa constituye una variable agroclimática relevante para el cultivo de cacao, debido a su influencia directa sobre los procesos fisiológicos de transpiración, balance hídrico de la planta y susceptibilidad a estrés combinado con altas temperaturas. De acuerdo con la literatura agronómica, el cacao presenta un desarrollo óptimo bajo condiciones de humedad relativa promedio comprendidas entre el 70 % y el 90 %, rangos que favorecen la actividad fotosintética y reducen el estrés hídrico atmosférico.

En este estudio, se definió el Estrés por Humedad Relativa diario como la condición en la cual la humedad relativa registrada se encuentra por debajo del umbral mínimo óptimo del 70 %, considerándose este valor como un límite inferior crítico para el cultivo. Bajo este criterio, cada día fue clasificado de forma binaria como día con estrés por humedad relativa o día sin estrés.

A partir de esta clasificación diaria, se construyó el Índice de Estrés por Humedad Relativa Mensual (EHR), definido como la proporción de días del mes que presentaron condiciones de estrés por humedad relativa. Este índice se expresa en una escala continua entre 0 y 1, donde valores cercanos a 0 indican meses con condiciones de humedad mayoritariamente favorables, mientras que valores cercanos a 1 representan meses con una alta recurrencia de condiciones de humedad relativa por debajo del rango óptimo para el cultivo de cacao.

Con el fin de facilitar la interpretación de los resultados, los valores del EHR fueron tipificados en tres rangos de riesgo agroclimático mensual: bajo, intermedio y alto. Se consideraron meses con bajo riesgo hídrico-atmosférico aquellos con valores de EHR inferiores a 0.40, riesgo intermedio los meses con valores entre 0.40 y 0.65, y riesgo alto aquellos con valores iguales o superiores a 0.65. Esta tipificación permite integrar el componente de humedad relativa dentro del análisis agroclimático mensual y fortalecer la evaluación del estrés ambiental que enfrenta el cultivo de cacao.

In [19]:
# ============================================================
# CONSTRUCCIÓN DEL ESTRÉS POR HUMEDAD RELATIVA (EHR)
# ============================================================

# --- Verificación de columnas necesarias ---
columnas_hr = ['hr', 'year_month']
for col in columnas_hr:
    if col not in df.columns:
        raise ValueError(f"La columna '{col}' no existe en el DataFrame diario")

# ============================================================
# 1️⃣ CÁLCULO DIARIO DE ESTRÉS POR HUMEDAD RELATIVA
# ============================================================

# Umbral mínimo óptimo para cacao (%)
HR_MIN_OPTIMO = 70

# Variable binaria diaria de estrés por humedad relativa
df['estres_hr_dia'] = (df['hr'] < HR_MIN_OPTIMO).astype(int)

# ============================================================
# 2️⃣ AGREGACIÓN MENSUAL DEL EHR
# ============================================================

ehr_mensual = (
    df.groupby('year_month')
      .agg(
          dias_mes=('estres_hr_dia', 'count'),
          dias_estres_hr=('estres_hr_dia', 'sum')
      )
      .reset_index()
)

# Cálculo del índice EHR mensual
ehr_mensual['EHR'] = ehr_mensual['dias_estres_hr'] / ehr_mensual['dias_mes']

# ============================================================
# 3️⃣ INTEGRACIÓN DEL EHR EN df_mensual
# ============================================================

df_mensual = df_mensual.merge(
    ehr_mensual[['year_month', 'EHR']],
    on='year_month',
    how='left'
)

# ============================================================
# 4️⃣ VALIDACIÓN RÁPIDA
# ============================================================

df_mensual[['EHR']].describe()

              EHR
count  174.000000
mean     0.041533
std      0.076793
min      0.000000
25%      0.000000
50%      0.000000
75%      0.035119
max      0.366667

In [20]:
df_mensual.head()

  year_month        ET        EH        ER  EHR
0    2010-01  0.325111  0.935484  0.870968  0.0
1    2010-02  0.239796  0.607143  0.035714  0.0
2    2010-03  0.276152  0.612903  0.032258  0.0
3    2010-04  0.510893  0.633333  0.033333  0.0
4    2010-05  0.500000  0.516129  0.064516  0.0

## Construcción de variable Objetivo

El Índice de Estrés Agroclimático Mensual del Cacao (IEAM-C) se definió como la variable objetivo del proyecto y se construyó mediante la integración de los principales factores climáticos que influyen en el desarrollo fisiológico y productivo del cultivo de cacao: el estrés térmico (ET), el estrés hídrico (EH), el estrés por radiación solar (ER) y el estrés por humedad relativa (EHR). Cada uno de estos componentes fue previamente calculado a escala mensual y normalizado en un rango entre 0 y 1, donde valores cercanos a 0 indican condiciones favorables y valores cercanos a 1 representan escenarios de mayor nivel de estrés.

La formulación del IEAM-C se realizó como una combinación ponderada de los índices parciales, asignando las ponderaciones en función de la relevancia agronómica de cada variable y de su recurrencia histórica en el área de estudio. En este sentido, el componente hídrico recibió el mayor peso debido a su impacto directo en la disponibilidad de agua para el cultivo, seguido por el estrés térmico y el estrés por radiación solar. El estrés por humedad relativa fue incorporado con una ponderación menor, dado que el análisis histórico evidenció una baja frecuencia de condiciones críticas asociadas a esta variable. Matemáticamente, el índice se expresa como:

𝐼
𝐸
𝐴
𝑀-
𝐶
=0.25
⋅
𝐸
𝑇
+
0.40
⋅
𝐸
𝐻
+
0.20
⋅
𝐸
𝑅
+
0.15
⋅
𝐸
𝐻
𝑅
IEAM-C=0.25⋅ET+0.40⋅EH+0.20⋅ER+0.15⋅EHR



Este índice integrado permite sintetizar el nivel de estrés agroclimático mensual y constituye una herramienta de apoyo a la planificación agrícola del cultivo de cacao, sin pretender realizar predicciones determinísticas del comportamiento climático futuro.

# Rangos


| IEAM-C               | Escenario  | Interpretación agroclimática                   |
| -------------------- | ---------- | ---------------------------------------------- |
| IEAM-C < 0.40        | Favorable  | Condiciones mayormente óptimas para el cultivo |
| 0.40 ≤ IEAM-C < 0.65 | Intermedio | Presencia de estrés agroclimático moderado     |
| IEAM-C ≥ 0.65        | Crítico    | Alto nivel de estrés agroclimático             |



# Impacto

| Componente | Peso     | Justificación                               |
| ---------- | -------- | ------------------------------------------- |
| EH         | **0.45** | Principal limitante del cacao               |
| ET         | **0.30** | Impacta floración y cuajado                 |
| ER         | **0.20** | Afecta fotosíntesis                         |
| EHR        | **0.05** | Favorece o limita enfermedades y fisiología |

In [21]:
# =========================================
# CONSTRUCCIÓN DE LA VARIABLE OBJETIVO IEAM-C
# =========================================

# Ponderaciones definidas según relevancia agronómica
w_EH  = 0.45   # Estrés hídrico
w_ET  = 0.30   # Estrés térmico
w_ER  = 0.20   # Estrés por radiación solar
w_EHR = 0.05   # Estrés por humedad relativa

# Cálculo del Índice de Estrés Agroclimático Mensual del Cacao
df_mensual['IEAM_C'] = (
    w_EH  * df_mensual['EH'] +
    w_ET  * df_mensual['ET'] +
    w_ER  * df_mensual['ER'] +
    w_EHR * df_mensual['EHR']
)

# =========================================
# CLASIFICACIÓN DE ESCENARIOS MENSUALES
# =========================================

def clasificar_ieam(valor):
    if valor < 0.45:
        return 'Favorable'
    elif valor < 0.60:
        return 'Intermedio'
    else:
        return 'Crítico'

df_mensual['Escenario_IEAM_C'] = df_mensual['IEAM_C'].apply(clasificar_ieam)

# =========================================
# ORDEN FINAL DE COLUMNAS
# =========================================

orden_columnas = [
    'year_month',
    'ET',
    'EH',
    'ER',
    'EHR',
    'IEAM_C',
    'Escenario_IEAM_C'
]

df_mensual = df_mensual[orden_columnas]

# Verificación
df_mensual.head()

  year_month        ET        EH        ER  EHR    IEAM_C Escenario_IEAM_C
0    2010-01  0.325111  0.935484  0.870968  0.0  0.692695          Crítico
1    2010-02  0.239796  0.607143  0.035714  0.0  0.352296        Favorable
2    2010-03  0.276152  0.612903  0.032258  0.0  0.365104        Favorable
3    2010-04  0.510893  0.633333  0.033333  0.0  0.444935        Favorable
4    2010-05  0.500000  0.516129  0.064516  0.0  0.395161        Favorable

In [22]:
df_mensual.head(20)

   year_month        ET        EH        ER  EHR    IEAM_C Escenario_IEAM_C
0     2010-01  0.325111  0.935484  0.870968  0.0  0.692695          Crítico
1     2010-02  0.239796  0.607143  0.035714  0.0  0.352296        Favorable
2     2010-03  0.276152  0.612903  0.032258  0.0  0.365104        Favorable
3     2010-04  0.510893  0.633333  0.033333  0.0  0.444935        Favorable
4     2010-05  0.500000  0.516129  0.064516  0.0  0.395161        Favorable
5     2010-06  0.579762  0.533333  0.000000  0.0  0.413929        Favorable
6     2010-07  0.682373  0.419355  0.032258  0.0  0.399873        Favorable
7     2010-08  0.626613  0.645161  0.032258  0.0  0.484758       Intermedio
8     2010-09  0.661548  0.300000  0.066667  0.0  0.346798        Favorable
9     2010-10  0.663018  0.612903  0.064516  0.0  0.487615       Intermedio
10    2010-11  0.767500  0.433333  1.000000  0.0  0.625250          Crítico
11    2010-12  0.785714  0.516129  0.161290  0.0  0.500230       Intermedio
12    2011-01  0.607316  0.741935  0.870968  0.0  0.690259          Crítico
13    2011-02  0.624872  0.750000  0.000000  0.0  0.524962       Intermedio
14    2011-03  0.683399  0.741935  0.000000  0.0  0.538891       Intermedio
15    2011-04  0.667262  0.733333  0.000000  0.0  0.530179       Intermedio
16    2011-05  0.644375  0.516129  0.000000  0.0  0.425571        Favorable
17    2011-06  0.614705  0.600000  0.000000  0.0  0.454411       Intermedio
18    2011-07  0.581339  0.709677  0.000000  0.0  0.493756       Intermedio
19    2011-08  0.524925  0.677419  0.000000  0.0  0.462316       Intermedio

In [23]:
# ============================================================
# IDENTIFICACIÓN DE MESES CRÍTICOS SEGÚN IEAM-C
# ============================================================

# Filtrar meses críticos
meses_criticos_ieam = df_mensual[
    df_mensual['Escenario_IEAM_C'] == 'Crítico'
][['year_month', 'IEAM_C']]

# Mostrar los primeros registros
meses_criticos_ieam.head()

   year_month    IEAM_C
0     2010-01  0.692695
10    2010-11  0.625250
12    2011-01  0.690259
22    2011-11  0.641055
24    2012-01  0.707340

In [24]:
# Total de meses analizados
total_meses = df_mensual.shape[0]

# Total de meses críticos
total_criticos = meses_criticos_ieam.shape[0]

# Porcentaje de meses críticos
porcentaje_criticos = (total_criticos / total_meses) * 100

total_criticos, porcentaje_criticos

(27, 15.517241379310345)

In [25]:
df_mensual.describe()

               ET          EH          ER         EHR      IEAM_C
count  174.000000  174.000000  174.000000  174.000000  174.000000
mean     0.491159    0.675659    0.256949    0.041533    0.504861
std      0.116921    0.135164    0.279322    0.076793    0.084673
min      0.106797    0.300000    0.000000    0.000000    0.346798
25%      0.421023    0.580645    0.000000    0.000000    0.441198
50%      0.493198    0.677995    0.116240    0.000000    0.496380
75%      0.555236    0.774194    0.466667    0.035119    0.551376
max      0.785714    0.935484    1.000000    0.366667    0.755240

In [26]:
# =========================================
# EXPORTAR df_mensual A EXCEL
# =========================================

nombre_archivo = 'df_mensual_IEAM_C_cacao.xlsx'

df_mensual.to_excel(nombre_archivo, index=False)

from google.colab import files
files.download(nombre_archivo)

In [27]:
# =========================================
# EXPORTAR df_mensual A CSV
# =========================================

nombre_archivo = 'df_mensual_IEAM_C_cacao.csv'

df_mensual.to_csv(nombre_archivo, index=False, encoding='utf-8')

# Descargar automáticamente en Colab
from google.colab import files
files.download(nombre_archivo)